# おまじない
# version: "3"
# コンテナの一覧を書く合図
services:
  # コンテナの名前
  cpp_tutorial:
    # このフォルダにあるDokerfileを使う
    build: .
    # ホストの"."とコンテナ内の"app"を同期（これがないとコンテナを消したらファイルが消える）
    volumes:
      - .:/workspace
    # ターミナルを使えるようにする設定
    tty: true
